# Generated by Django 3.2.6 on 2021-08-06 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='art_description',
            field=models.TextField(max_length=1000),
        ),
    ]
