# Generated by Django 3.2.6 on 2021-08-06 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_art_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='art_description',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
