# Generated by Django 3.2.6 on 2021-08-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_orderitem_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
